author: Gaioli
database: false
description: Let users protect their own land with RedStone Protection. Hooks into
  WorldGuard and Vault to allow users to buy protection from the server.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.gaioli.plugins.redstoneprotect.RedstoneProtect
name: RedStoneProtect
startup: postworld
url: http://diamondcraft.co/
version: '1.1'
depends: [WorldEdit, WorldGuard, Vault]
permissions:
  rp.*:
    description: Allows access to all RedStone Protection permissions
    children:
      rp.protect.vip: true
      rp.protect.block: true
  rp.protect.vip:
    description: Allows the user to buy/make 40x40 regions
    default: op
  rp.protect.block:
    description: Allows the user to buy/make 10x10 and 20x20 regions
    default: op
      